# Generated by Django 2.2.4 on 2019-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('pdfpass', models.CharField(max_length=255, verbose_name='pdfpass')),
                ('topimg', models.CharField(max_length=255, verbose_name='topimg')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
    ]
